# Generated by Django 6.0.2 on 2026-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("Call/WhatsApp", "Call/WhatsApp"),
                            ("LinkedIn", "LinkedIn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
